### PR TITLE
ActionController dismiss on background added

### PR DESCRIPTION
**Pull request by farri**
Dear,

I've added 2 features to this project:
1. UITextFields on ActionSheet and moving action sheet to top on textField click
2. Dismissing ActionController on Background click.

### CODE REVIEW

**Comment by CooperRS** [comment]
Hey!

Thank your for your pull request. In psrticular, the keyboard supports sounds interesting :). I'll review your pull request asap.

However, background taps should already be supported. You only need to add a cancel action who's handler will be called when a tap on the blurred background is recognized. Have you checked that?

Best regards,
Roland

**Comment by yasirmturk** [comment]
It is good if you dont have cancel action in the design and only way to dismiss is to tap the background

**Comment by CooperRS** [comment]
But in this case, you then have no delegate is being called when the action controller is dismissed (may be a problem bust does not have to).

However, you might be right, that in cases with no cancel button this functionality might be useful. But these cases should be handled by the same gesture recognizer that recognizes all other taps on the background view. It's handler is implemented in ```- (void)backgroundViewTapped:(UIGestureRecognizer *)sender```. In addition, an option to disable this behaviour might be nice, as well :)

**Comment by yasirmturk** [comment]
You are right @CooperRS , 
it should be handled by same gesture recognizer and 
should call the same delegate and 
it should be possible to disable the behaviour @farri

**Pull request closed without merging**
